### ISSUE TITLE
CommandLog doesn't provide interface to file stats

### ISSUE THREAD

**Issue by onorua** [kellabyte/rewind#6]
https://github.com/kellabyte/rewind/blob/2c5f1749381f42c8124eb1be53121ceff350aaf2/commandlog/command_log.go#L12

spf13/afero does support file interface, which could be used for file information analysis, such as Stats, Name, etc, which could be used to build file rotation bases on file size and so on.  At the moment file is private. 
Is this something you explicitly want to be hided, or you would accept a PR fixing this?

**Comment by kellabyte** [comment]
Closing because the project has changed direction.
